AUGMENTATION: True
IMAGE_SIZE: [224,224,3] # as per VGG 16 model -> see the documentation
BATCH_SIZE: 16
INCLUDE_TOP: False # because I don't want to take FC layers of VGG 16 model
EPOCHS: 1
CLASSES: 2 
WEIGHTS: imagenet
LEARNING_RATE: 0.01